"""Distributed Agent Harness — shared, auditable world state for multi-agent systems."""

from .conflict import (
    Abandon,
    AgentDrivenConflictResolver,
    AlwaysRecoverResolver,
    ConcurrentUpdate,
    ConflictContext,
    ConflictResolver,
    Continue,
    Decision,
    Recover,
    ScriptedResolver,
)
from .event_search import EventQuery, render_events_markdown, search_events
from .namespace_browse import (
    DirEntry,
    GrepMatch,
    grep_docs,
    list_dir,
    read_doc,
    render_grep,
    render_ls,
    render_read,
)
from .eventlog import (
    Appended,
    AppendResult,
    Conflict,
    Event,
    EventLog,
    InMemoryEventLog,
)
from .hooks import (
    ActionContext,
    ActionErrorHook,
    BlockDecision,
    HookRegistry,
    PostActionHook,
    PostSubagentCallHook,
    PreActionHook,
    PreSubagentCallHook,
    PreTriggerHook,
    RunCompleteHook,
    SubagentContext,
)
from .llm import (
    CompletionChunk,
    LLMProvider,
    Message,
    Role,
    ToolCall,
    ToolSchema,
)
from .namespace import DocInfo, NamespaceAdapter
from .prompt_builder import PromptBuilder
from .runtime import AgentRuntime
from .subagents import (
    A2ASubagent,
    AgentCard,
    AgentRegistry,
    Artefact,
    AsyncSubagent,
    HttpAgentRegistry,
    InMemoryMessageBus,
    InProcessSubagent,
    MessageBus,
    MessagingSubagent,
    MessagingSubagentWorker,
    NoSubscriberError,
    Skill,
    StaticAgentRegistry,
    SubagentClient,
    SubagentRegistry,
    SubagentResponse,
    SubagentTimeout,
    Subscription,
    load_subagents_from_registry,
)
from .transport import (
    OutputChannel,
    OutputEvent,
    OutputEventKind,
    TriggerEvent,
    TriggerKind,
    TriggerSource,
)
from .world import ActionNotAvailable, BaseWorldEnvironment, Predicate, action

__all__ = [
    # Core
    "BaseWorldEnvironment",
    "action",
    "Predicate",
    "ActionNotAvailable",
    "NamespaceAdapter",
    "DocInfo",
    "PromptBuilder",
    # Event sourcing
    "Event",
    "EventLog",
    "InMemoryEventLog",
    "Appended",
    "Conflict",
    "AppendResult",
    # Conflict resolution
    "ConcurrentUpdate",
    "ConflictContext",
    "ConflictResolver",
    "AgentDrivenConflictResolver",
    "AlwaysRecoverResolver",
    "ScriptedResolver",
    "Decision",
    "Continue",
    "Recover",
    "Abandon",
    # LLM
    "LLMProvider",
    "Message",
    "Role",
    "ToolCall",
    "ToolSchema",
    "CompletionChunk",
    # Transport
    "TriggerEvent",
    "TriggerKind",
    "TriggerSource",
    "OutputEvent",
    "OutputEventKind",
    "OutputChannel",
    # Hooks
    "HookRegistry",
    "ActionContext",
    "SubagentContext",
    "BlockDecision",
    "PreActionHook",
    "PostActionHook",
    "ActionErrorHook",
    "PreTriggerHook",
    "RunCompleteHook",
    "PreSubagentCallHook",
    "PostSubagentCallHook",
    # Event search
    "EventQuery",
    "search_events",
    "render_events_markdown",
    # Namespace browsing
    "DirEntry",
    "GrepMatch",
    "list_dir",
    "read_doc",
    "grep_docs",
    "render_ls",
    "render_read",
    "render_grep",
    # Subagents
    "SubagentClient",
    "SubagentResponse",
    "SubagentRegistry",
    "SubagentTimeout",
    "Artefact",
    "AgentCard",
    "Skill",
    "A2ASubagent",
    "AgentRegistry",
    "StaticAgentRegistry",
    "HttpAgentRegistry",
    "load_subagents_from_registry",
    # In-process subagents
    "InProcessSubagent",
    "AsyncSubagent",
    "MessageBus",
    "InMemoryMessageBus",
    "MessagingSubagent",
    "MessagingSubagentWorker",
    "NoSubscriberError",
    "Subscription",
    # Runtime
    "AgentRuntime",
]
